export const syllabus = {
  "Advanced Accounting": [
    "Ch 1 - Introduction to Accounting Standards",
    "Ch 2 - Framework for Preparation and Presentation of Financial Statements",
    "Ch 3 - Applicability of Accounting Standards",
    "AS 1 - Disclosure of Accounting Policies",
    "AS 3 - Cash Flow Statements",
    "AS 17 - Segment Reporting",
    "AS 18 - Related Party Disclosures",
    "AS 20 - Earnings Per Share",
    "AS 24 - Discontinuing Operations",
    "AS 25 - Interim Financial Reporting",
    "AS 2 - Valuation of Inventories",
    "AS 10 - Property, Plant and Equipment",
    "AS 13 - Accounting for Investments",
    "AS 16 - Borrowing Costs",
    "AS 19 - Leases",
    "AS 26 - Intangible Assets",
    "AS 28 - Impairment of Assets",
    "AS 15 - Employee Benefits",
    "AS 29 - Provisions, Contingent Liabilities and Contingent Assets",
    "AS 4 - Contingencies and Events Occurring after the Balance Sheet Date",
    "AS 5 - Net Profit/Loss, Prior Period Items and Changes in Accounting Policies",
    "AS 11 - Effects of Changes in Foreign Exchange Rates",
    "AS 22 - Accounting for Taxes on Income",
    "AS 7 - Construction Contracts",
    "AS 9 - Revenue Recognition",
    "AS 12 - Accounting for Government Grants",
    "AS 14 - Accounting for Amalgamations",
    "AS 21 - Consolidated Financial Statements",
    "AS 23 - Investments in Associates in Consolidated Financial Statements",
    "AS 27 - Financial Reporting of Interests in Joint Ventures",
    "Ch 11 - Financial Statements of Companies",
    "Ch 12 - Buyback of Securities",
    "Ch 13 - Amalgamation of Companies",
    "Ch 14 - Internal Reconstruction",
    "Ch 15 - Accounting for Branches including Foreign Branches"
  ],
  "Corporate and Other Laws": [
    "Company Law - Ch 1: Preliminary",
    "Company Law - Ch 2: Incorporation of Company and Matters Incidental Thereto",
    "Company Law - Ch 3: Prospectus and Allotment of Securities",
    "Company Law - Ch 4: Share Capital and Debentures",
    "Company Law - Ch 5: Acceptance of Deposits by Companies",
    "Company Law - Ch 6: Registration of Charges",
    "Company Law - Ch 7: Management & Administration",
    "Company Law - Ch 8: Declaration and Payment of Dividend",
    "Company Law - Ch 9: Accounts of Companies",
    "Company Law - Ch 10: Audit and Auditors",
    "Company Law - Ch 11: Companies Incorporated Outside India",
    "LLP - Ch 12: The Limited Liability Partnership Act, 2008",
    "Other Laws - Ch 1: The General Clauses Act, 1897",
    "Other Laws - Ch 2: Interpretation of Statutes",
    "Other Laws - Ch 3: The Foreign Exchange Management Act, 1999"
  ],
  "Taxation": [
    "Income Tax - Ch 1: Basic Concepts",
    "Income Tax - Ch 2: Residence and Scope of Total Income",
    "Income Tax - Ch 3.1: Salaries",
    "Income Tax - Ch 3.2: Income from House Property",
    "Income Tax - Ch 3.3: Profits and Gains of Business or Profession",
    "Income Tax - Ch 3.4: Capital Gains",
    "Income Tax - Ch 3.5: Income from Other Sources",
    "Income Tax - Ch 4: Income of Other Persons included in Assessee's Total Income",
    "Income Tax - Ch 5: Aggregation, Set-Off and Carry Forward of Losses",
    "Income Tax - Ch 6: Deductions from Gross Total Income",
    "Income Tax - Ch 7: Advance Tax, TDS and TCS",
    "Income Tax - Ch 8: Return of Income and Self Assessment",
    "Income Tax - Ch 9: Income Tax Liability - Computation and Optimisation",
    "GST - Ch 1: GST in India - An Introduction",
    "GST - Ch 2: Supply under GST",
    "GST - Ch 3: Charge of GST",
    "GST - Ch 4: Place of Supply",
    "GST - Ch 5: Exemptions from GST",
    "GST - Ch 6: Time of Supply",
    "GST - Ch 7: Value of Supply",
    "GST - Ch 8: Input Tax Credit",
    "GST - Ch 9: Registration",
    "GST - Ch 10: Tax Invoice; Credit and Debit Notes",
    "GST - Ch 11: Accounts and Records",
    "GST - Ch 12: E-Way Bill",
    "GST - Ch 13: Payment of Tax",
    "GST - Ch 14: Tax Deduction at Source and Collection of Tax at Source",
    "GST - Ch 15: Returns"
  ],
  "Cost and Management Accounting": [
    "Ch 1 - Introduction to Cost and Management Accounting",
    "Ch 2 - Material Cost",
    "Ch 3 - Employee Cost and Direct Expenses",
    "Ch 4 - Overheads - Absorption Costing Method",
    "Ch 5 - Activity Based Costing",
    "Ch 6 - Cost Sheet",
    "Ch 7 - Cost Accounting Systems",
    "Ch 8 - Unit & Batch Costing",
    "Ch 9 - Job Costing",
    "Ch 10 - Process & Operation Costing",
    "Ch 11 - Joint Products and By Products",
    "Ch 12 - Service Costing",
    "Ch 13 - Standard Costing",
    "Ch 14 - Marginal Costing",
    "Ch 15 - Budgets and Budgetary Control"
  ],
  "Auditing and Ethics": [
    "Ch 1 - Nature, Objective and Scope of Audit",
    "Ch 2 - Audit Strategy, Audit Planning and Audit Programme",
    "Ch 3 - Risk Assessment and Internal Control",
    "Ch 4 - Audit Evidence",
    "Ch 5 - Audit of Items of Financial Statements",
    "Ch 6 - Audit Documentation",
    "Ch 7 - Completion and Review",
    "Ch 8 - Audit Report",
    "Ch 9 - Special Features of Audit of Different Type of Entities",
    "Ch 10 - Audit of Banks",
    "Ch 11 - Ethics and Terms of Audit Engagements"
  ],
  "Financial Management & Strategic Management": [
    "FM - Ch 1: Scope and Objectives of Financial Management",
    "FM - Ch 2: Types of Financing",
    "FM - Ch 3: Financial Analysis and Planning - Ratio Analysis",
    "FM - Ch 4: Cost of Capital",
    "FM - Ch 5: Financing Decisions - Capital Structure",
    "FM - Ch 6: Financing Decisions - Leverages",
    "FM - Ch 7: Investment Decisions",
    "FM - Ch 8: Dividend Decision",
    "FM - Ch 9: Management of Working Capital",
    "SM - Ch 1: Introduction to Strategic Management",
    "SM - Ch 2: Strategic Analysis - External Environment",
    "SM - Ch 3: Strategic Analysis - Internal Environment",
    "SM - Ch 4: Strategic Choices",
    "SM - Ch 5: Strategy Implementation and Evaluation"
  ]
} as const;
export type SubjectName = keyof typeof syllabus;
