-- CA Progress secure admin foundation (non-destructive: creates new objects only).
-- After running this file, replace the UUID below and run the final INSERT once.

create extension if not exists pgcrypto;

create table if not exists public.subscription_plans (
  id uuid primary key default gen_random_uuid(),
  slug text unique not null,
  name text not null,
  rank integer unique not null check (rank >= 0),
  price_monthly numeric(10,2) not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

insert into public.subscription_plans (slug,name,rank,price_monthly)
values ('free','Free',0,0),('pro','Pro',10,0),('premium','Premium',20,0)
on conflict (slug) do nothing;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('owner','admin','moderator')),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

create table if not exists public.user_subscriptions (
  user_id uuid primary key references auth.users(id) on delete cascade,
  plan_id uuid not null references public.subscription_plans(id),
  status text not null default 'active' check (status in ('active','trialing','paused','cancelled','expired')),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.app_sections (
  id uuid primary key default gen_random_uuid(),
  section_key text unique not null,
  label text not null,
  description text not null default '',
  route text not null,
  enabled boolean not null default true,
  audience text not null default 'all' check (audience in ('all','guest','member')),
  minimum_plan_rank integer not null default 0,
  sort_order integer not null default 100,
  starts_at timestamptz,
  ends_at timestamptz,
  appearance jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

insert into public.app_sections(section_key,label,description,route,sort_order)
values
('dashboard','Dashboard','Preparation overview','/dashboard',10),
('community','Community','Course-based student discussions','/community',20),
('subjects','Subjects','Subject progress','/subjects',30),
('chapters','Chapters','Chapter tracking','/chapters',40),
('analytics','Analytics','Progress analytics','/analytics',50),
('study-sessions','Study Sessions','Study time records','/study-sessions',60),
('goals','Goals','Preparation goals','/goals',70),
('test-series','Test Series','Test performance','/test-series',80),
('calendar','Calendar','Study calendar','/calendar',90),
('activity','Activity','Progress history','/activity',100),
('notes','Notes','Personal notes','/notes',110),
('settings','Settings','Account and course preferences','/settings',120)
on conflict (section_key) do nothing;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id),
  action text not null,
  target_type text not null,
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin(required_roles text[] default array['owner','admin','moderator'])
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.admin_users where user_id=auth.uid() and role=any(required_roles)); $$;

alter table public.subscription_plans enable row level security;
alter table public.admin_users enable row level security;
alter table public.user_subscriptions enable row level security;
alter table public.app_sections enable row level security;
alter table public.admin_audit_logs enable row level security;

create policy "plans readable" on public.subscription_plans for select using (true);
create policy "plans managed by owners and admins" on public.subscription_plans for all using (public.is_admin(array['owner','admin'])) with check (public.is_admin(array['owner','admin']));
create policy "admins read own or admin list" on public.admin_users for select using (user_id=auth.uid() or public.is_admin(array['owner','admin']));
create policy "owners manage admins" on public.admin_users for all using (public.is_admin(array['owner'])) with check (public.is_admin(array['owner']));
create policy "subscriptions read own" on public.user_subscriptions for select using (user_id=auth.uid() or public.is_admin(array['owner','admin']));
create policy "subscriptions managed by admins" on public.user_subscriptions for all using (public.is_admin(array['owner','admin'])) with check (public.is_admin(array['owner','admin']));
create policy "sections readable" on public.app_sections for select using (true);
create policy "sections managed by admins" on public.app_sections for all using (public.is_admin(array['owner','admin'])) with check (public.is_admin(array['owner','admin']));
create policy "audit readable by owners" on public.admin_audit_logs for select using (public.is_admin(array['owner']));
create policy "admins write audit" on public.admin_audit_logs for insert with check (public.is_admin());

-- Allows appointed moderators/admins to remove community messages.
create policy "moderators delete community messages"
on public.community_messages for delete
using (public.is_admin(array['owner','admin','moderator']));

-- BOOTSTRAP OWNER (run separately after replacing the UUID):
-- insert into public.admin_users(user_id,role) values ('REPLACE_WITH_YOUR_SUPABASE_USER_UUID','owner');
